version: '3'
services:
    nginx-router:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'    
    expressapi:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - /myproj/server:/app
        env_file:
            - ./complexConfig.env
        #could also directly specify env vars here
        #environment:
            #VARNAME=VARVALUE
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - /myproj/client:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - /myproj/worker:/app
        env_file:
            - ./complexConfig.env

